spring.application.name=product-inventory
server.port=5000

# spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/productdb}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root123}
spring.datasource.url=jdbc:h2:mem:productdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect



spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.product_inventory=INFO
